### ISSUE TITLE
Chord Diagram is not getting updated after selecting acl action as Deny

### ISSUE THREAD

**Issue by natabal** [nuagenetworks/vis-graphs#203]
There are 2 ACL action types by default Allow is selected however when selecting the other option (deny) the chord diagram does not get updated.

**Comment by natabal** [comment]
![Deny_Overlay_Underlay (1)](https://user-images.githubusercontent.com/4873481/61635346-38ad1200-ac48-11e9-9906-6f059416748e.gif)

**Comment by nxjiten** [comment]
@natabal 
Please provide the data as discussed on call to reproduce the above issue.
Thanks

**Comment by natabal** [comment]
@AnamikaDubey07 Can you please generate some data for @nxjiten to debug?

**Comment by AnamikaDubey07** [comment]
@natabal sure i am in touch with @nxjiten 
I have data in testbed, will ask him what details he needs from my side.

**Comment by AnamikaDubey07** [comment]
![image](https://user-images.githubusercontent.com/53247988/62032807-37f81b00-b208-11e9-963e-e9b932700b06.png)

**Comment by nxjiten** [comment]
@AnamikaDubey07 
As discussed, please provide the JSON data to reproduce the same issue.

**Comment by AnamikaDubey07** [comment]
![Deny_Overlay_Underlay](https://user-images.githubusercontent.com/53247988/62045717-b4e4be00-b223-11e9-9734-87d84ba44d10.gif)
[Deny_Overlay_Underlay.txt](https://github.com/nuagenetworks/vis-graphs/files/3441852/Deny_Overlay_Underlay.txt)
[Nuage_Flow.txt](https://github.com/nuagenetworks/vis-graphs/files/3441853/Nuage_Flow.txt)

**Comment by nxjiten** [comment]
@natabal @AnamikaDubey07 

I have tested the chord graph by using the data provided by Anamika and found that everything working fine as expected.

The data is not coming in case of `DENY` because there are other filters in query which filter out all `DENY` data as given below: - 

![Screenshot from 2019-07-30 18-02-24](https://user-images.githubusercontent.com/49763726/62129554-9bf80d80-b2f4-11e9-9e27-149e0931f772.png)

In above screenshot, there is no data of `DENY` ( `nuage_metadata.actions.type: DENY`) when other fields have  `nuage_metadata.direction: ingress`   and `underlayflow: true` ,  so it is returning empty array.
let me know if I am missing anything.

**Comment by natabal** [comment]
@nxjiten There are 2 diagrams: overlay and underlay! The above configuration is for the Underlay diagram. For the overlay diagram use vss-domain-flow.json query.

**Comment by nxjiten** [comment]
@natabal 

I have tested the overlay diagram and yes data is coming when we select `DENY`, but in that case either `source` field or `destination` field is coming null from the data provided by @AnamikaDubey07  and it will be filtered out in `parseData` method as given below in screenshot:

![02286d583715cb837e48c908705de6dc](https://user-images.githubusercontent.com/49763726/62194853-4e34e100-b398-11e9-98e7-c1aa2ccf2149.png)

**Comment by natabal** [comment]
@AnamikaDubey07 Can you please investigate why is the source/destination null? Thanks!
