### ISSUE TITLE
Multiple Heatmaps on a Dashboard not rendering intermittently

### ISSUE THREAD

**Issue by chaitanyahalbe** [nuagenetworks/vis-graphs#405]
I have multiple heatmaps on 1 dashboard in PR - https://github.com/nuagenetworks/vis-config/pull/202 (associated js-bambou PR - https://github.com/nuagenetworks/js-bambou/pull/174).

Problem #1: All 3 heatmaps on the dashboard should render at once after selecting proper filters. But only a few of them get rendered at once. Rarely, all 3 will get rendered. All the queries are returning data.

Problem #2: I have listeners in all the above 3 heatmaps, so that when a heatmap cell is clicked, a corresponding table is rendered showing details of that cell. But the problem is, upon clicking a cell on heatmap #1, all 3 tables for all the heatmaps get re-rendered even though I have different variable names, query-ids and visualizations for all 3 tables. Expected behaviour is, when a cell on heatmap #1 is clicked, only table #1 should get rendered/re-rendered.

**Comment by chaitanyahalbe** [comment]
@natabal @nxanil Created issue for multiple heatmaps.

**Comment by natabal** [comment]
@nxanil This issue is seen in other areas as well not just for this situation alone. See attached screenshots:

![ike-tab-1](https://user-images.githubusercontent.com/4873481/92048866-a4afe400-ed3d-11ea-9cb7-f9286f0fe130.PNG)
![ike-tab-2](https://user-images.githubusercontent.com/4873481/92048872-a679a780-ed3d-11ea-94e4-a1b4cb323dd9.PNG)
![image-2020-09-02-15-53-14-006](https://user-images.githubusercontent.com/4873481/92048876-a7aad480-ed3d-11ea-97f6-86b2d0003c3b.png)

**Comment by killanch** [comment]
@chaitanyahalbe could you pls check and confirm if this issue has been fixed in above commit?

**Comment by chaitanyahalbe** [comment]
> @chaitanyahalbe could you pls check and confirm if this issue has been fixed in above commit?

@killanch This has already been verified. I'll close this.
